//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace carrito_apl_proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cargo_ciudades
    {
        public int pk_cargo_ciudades { get; set; }
        public Nullable<int> fk_transporte { get; set; }
        public int fk_ciudad { get; set; }
        public decimal costo { get; set; }
    
        public virtual ciudades ciudades { get; set; }
        public virtual transportes transportes { get; set; }
    }
}
