//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace carrito_apl_proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class categorias
    {
        public categorias()
        {
            this.productos = new HashSet<productos>();
        }
    
        public int pk_categoria { get; set; }
        public string tag { get; set; }
    
        public virtual ICollection<productos> productos { get; set; }
    }
}
