//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace carrito_apl_proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ciudades
    {
        public ciudades()
        {
            this.cargo_ciudades = new HashSet<cargo_ciudades>();
            this.direcciones = new HashSet<direcciones>();
        }
    
        public int pk_ciudad { get; set; }
        public int fk_departamento { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<cargo_ciudades> cargo_ciudades { get; set; }
        public virtual departamentos departamentos { get; set; }
        public virtual ICollection<direcciones> direcciones { get; set; }
    }
}
