//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace carrito_apl_proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class compradores
    {
        public compradores()
        {
            this.direcciones = new HashSet<direcciones>();
            this.facturas = new HashSet<facturas>();
            this.tarjetas = new HashSet<tarjetas>();
            this.sesiones = new HashSet<sesiones>();
        }
    
        public string pk_comprador { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public string tipo_documento { get; set; }
        public string celular { get; set; }
        public string genero { get; set; }
        public string password { get; set; }
    
        public virtual ICollection<direcciones> direcciones { get; set; }
        public virtual ICollection<facturas> facturas { get; set; }
        public virtual ICollection<tarjetas> tarjetas { get; set; }
        public virtual ICollection<sesiones> sesiones { get; set; }
    }
}
