//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace carrito_apl_proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class direcciones
    {
        public int pk_direccion { get; set; }
        public string fk_comprador { get; set; }
        public int fk_ciudad { get; set; }
        public string tag { get; set; }
        public string nombre_receptor { get; set; }
        public string celular { get; set; }
        public string direccion { get; set; }
    
        public virtual ciudades ciudades { get; set; }
        public virtual compradores compradores { get; set; }
    }
}
