//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace carrito_apl_proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos
    {
        public productos()
        {
            this.especificaciones = new HashSet<especificaciones>();
            this.items = new HashSet<items>();
        }
    
        public int pk_producto { get; set; }
        public int fk_transporte { get; set; }
        public int fk_categoria { get; set; }
        public string fotos { get; set; }
        public decimal descuento { get; set; }
        public decimal precio { get; set; }
        public decimal existencias { get; set; }
        public string titulo { get; set; }
        public string descripcion { get; set; }
    
        public virtual categorias categorias { get; set; }
        public virtual ICollection<especificaciones> especificaciones { get; set; }
        public virtual ICollection<items> items { get; set; }
        public virtual transportes transportes { get; set; }
    }
}
