//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace carrito_apl_proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sesiones
    {
        public int pk_sesiones { get; set; }
        public string fk_comprador { get; set; }
        public string ip { get; set; }
        public System.DateTime fecha_login { get; set; }
        public Nullable<System.DateTime> fecha_logout { get; set; }
    
        public virtual compradores compradores { get; set; }
    }
}
