//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace carrito_apl_proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tarjetas
    {
        public tarjetas()
        {
            this.facturas = new HashSet<facturas>();
        }
    
        public int pk_tarjeta { get; set; }
        public string fk_comprador { get; set; }
        public string numero_tarjeta { get; set; }
        public string nombre { get; set; }
        public System.DateTime fecha_vencimiento { get; set; }
        public string CVV { get; set; }
    
        public virtual compradores compradores { get; set; }
        public virtual ICollection<facturas> facturas { get; set; }
    }
}
