//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace carrito_apl_proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transportes
    {
        public transportes()
        {
            this.cargo_ciudades = new HashSet<cargo_ciudades>();
            this.productos = new HashSet<productos>();
        }
    
        public int pk_transporte { get; set; }
        public string nombres { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<cargo_ciudades> cargo_ciudades { get; set; }
        public virtual ICollection<productos> productos { get; set; }
    }
}
